export const SET_KC = 'SET_KC'
export const SET_ETO = 'SET_ETO'
export const SET_DWI = 'SET_DWI'
export const SET_EFFECTIVE_RAINFALL = 'SET_EFFECTIVE_RAINFALL'
export const SET_DAILY_PRECIPITATION = 'SET_DAILY_PRECIPITATION'
export const SET_SYSTEM_IRRIGATION_EFFICIENCY = 'SET_SYSTEM_IRRIGATION_EFFICIENCY'

export const RESET_ETO = 'RESET_ETO'